name: Aula Workflow Manual

on: 
  # push:
  #   branches:
  #     - main
  # schedule:
  #     - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      rodar_testes:
        description: 'Rodar testes antes do deploy?'
        required: true
        default: 'nao'
        type: choice
        options:
          - sim
          - nao

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configura versão do Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'        

      - name: Instalar dependências
        run: npm install

      - name: Executar build
        run: npm run build

      - name: Rodar testes
        if: ${{ github.event.inputs.rodar_testes == 'sim' }}
        run: |
          npm test
          echo "testes executados"